CU-86a0yz7tw - Add calculateFee method on Neo3Invoker to be used on W…
CityOfZion/neon-dappkit pull request #19
Opened 2023-09-29 20:29 UTC by endkeyCoder

…cSdk

2023-09-29 20:29 UTC, melanke commented
Task linked: [CU-86a0yz7tw Add calculateFee method on Neo3Invoker to be used on WcSdk](https://app.clickup.com/t/86a0yz7tw)

2023-10-02 14:06 UTC, melanke requested changes

2023-10-02 14:06 UTC, melanke commented on common/changes/@cityofzion/neon-dappkit-types/CU-86a0yz7tw-2_2023-09-29-20-41.json
> +      "comment": "It has been exported, the 'calculateFee' function in the Neo3Invoker interface.",
ALWAYS use Google translate to write these sentences

2023-10-02 14:06 UTC, melanke commented on common/changes/@cityofzion/neon-dappkit/CU-86a0yz7tw-2_2023-09-29-20-41.json
> +      "comment": "Now, the 'calculateFee' function returns a string in the 'networkFee' and 'systemFee' properties.",
here too

2023-10-02 15:17 UTC, endkeyCoder commented
can you close this PR? The same solution was implemented here -> https://github.com/CityOfZion/neon-dappkit/pull/20

2023-10-02 16:29 UTC, closed without merging