Cu 86a0gevc3
CityOfZion/neon-dappkit pull request #6
Opened 2023-08-28 19:15 UTC by endkeyCoder

2023-08-28 19:15 UTC, melanke commented
Task linked: [CU-86a0gevc3 Change WalletConnectSDK to use neon-dappkit](https://app.clickup.com/t/86a0gevc3)

2023-08-30 18:25 UTC, melanke requested changes

2023-08-30 18:25 UTC, melanke commented on packages/neon-dappkit/src/NeonSigner.spec.ts
> +      assert.ok(error instanceof Error)
The correct way to assign the error is thrown on async methods is like this:
https://github.com/CityOfZion/letter-core/blob/main/sdk/src/authenticators/Authenticator.spec.ts#L190

2023-08-30 18:25 UTC, melanke commented on common/changes/@cityofzion/neon-dappkit-types/CU-86a0gevc3_2023-08-28-19-24.json
> +      "comment": "Change WalletConnectSDK to use neon-dappkit - added Promise to type return on methods encrypt, descrypt and decryptFromArray",
```suggestion
      "comment": "Return Promises on encrypt, descrypt and decryptFromArray methods",
```

2023-08-30 18:25 UTC, melanke commented on common/changes/@cityofzion/neon-dappkit/CU-86a0gevc3_2023-08-28-19-24.json
> +      "comment": "Change WalletConnectSDK to use neon-dappkit - added Promise to type return on methods encrypt, descrypt and decryptFromArray",
```suggestion
      "comment": "Adapt the implementation to the new signature of neon-dappkit-types to return Promises on encrypt, descrypt and decryptFromArray methods",
```

2023-08-30 18:25 UTC, melanke commented on packages/neon-dappkit/package.json
> +    "@cityofzion/neon-dappkit-types": "workspace:*",
I think you will need to keep this as 0.0.3 instead of workspace:*
Let me know if this is causes a problem.

2023-08-30 18:25 UTC, melanke commented on packages/neon-dappkit/src/NeonSigner.spec.ts
> +      assert.ok(error instanceof Error)
Same thing here

2023-08-30 23:45 UTC, endkeyCoder commented on packages/neon-dappkit/src/NeonSigner.spec.ts
> +      assert.ok(error instanceof Error)
I did the same as the example now

2023-08-30 23:46 UTC, endkeyCoder commented on common/changes/@cityofzion/neon-dappkit-types/CU-86a0gevc3_2023-08-28-19-24.json
> +      "comment": "Change WalletConnectSDK to use neon-dappkit - added Promise to type return on methods encrypt, descrypt and decryptFromArray",
I changed the message to the message of suggestion

2023-08-30 23:47 UTC, endkeyCoder commented on packages/neon-dappkit/package.json
> +    "@cityofzion/neon-dappkit-types": "workspace:*",
I fixed it, now the neon-dappkit-types is 0.0.3 version

2023-08-30 23:48 UTC, endkeyCoder commented on packages/neon-dappkit/src/NeonSigner.spec.ts
> +      assert.ok(error instanceof Error)
I did the same as the example now

2023-08-31 11:07 UTC, merged